API_HOST_URL: 'https://vbc.fostudies.top'
ENVIRONMENT_DISPLAY_NAME: 'Vimalakirti Buddha College'
PLATFORM_NAME: 'Vimalakirti Buddha College'
PLATFORM_DESTINATION_NAME: 'vbc.fostudies.top'
FEEDBACK_EMAIL_ADDRESS: 'maxpos@163.com'
COURSE_VIDEOS_ENABLED: true
CERTIFICATES_ENABLED: true
DISCOVERY:
   COURSE:
     TYPE: 'native'
DISCUSSIONS_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
USER_PROFILES_ENABLED: true
VIDEO_TRANSCRIPT_ENABLED: true

